/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsJobIdRouteImport } from './routes/reviews_.$jobId'
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId'
import { Route as BatchesBatchIdReviewRouteImport } from './routes/batches_.$batchId.review'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsJobIdRoute = ReviewsJobIdRouteImport.update({
  id: '/reviews_/$jobId',
  path: '/reviews/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdReviewRoute = BatchesBatchIdReviewRouteImport.update({
  id: '/batches_/$batchId/review',
  path: '/batches/$batchId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/batches': typeof BatchesRoute
  '/jobs': typeof JobsRoute
  '/pipelines': typeof PipelinesRoute
  '/reviews': typeof ReviewsRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/reviews/$jobId': typeof ReviewsJobIdRoute
  '/batches/$batchId/review': typeof BatchesBatchIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/batches': typeof BatchesRoute
  '/jobs': typeof JobsRoute
  '/pipelines': typeof PipelinesRoute
  '/reviews': typeof ReviewsRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/reviews/$jobId': typeof ReviewsJobIdRoute
  '/batches/$batchId/review': typeof BatchesBatchIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/batches': typeof BatchesRoute
  '/jobs': typeof JobsRoute
  '/pipelines': typeof PipelinesRoute
  '/reviews': typeof ReviewsRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/jobs_/$jobId': typeof JobsJobIdRoute
  '/reviews_/$jobId': typeof ReviewsJobIdRoute
  '/batches_/$batchId/review': typeof BatchesBatchIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/batches'
    | '/jobs'
    | '/pipelines'
    | '/reviews'
    | '/schemas'
    | '/settings'
    | '/templates'
    | '/webhooks'
    | '/jobs/$jobId'
    | '/reviews/$jobId'
    | '/batches/$batchId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/batches'
    | '/jobs'
    | '/pipelines'
    | '/reviews'
    | '/schemas'
    | '/settings'
    | '/templates'
    | '/webhooks'
    | '/jobs/$jobId'
    | '/reviews/$jobId'
    | '/batches/$batchId/review'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/batches'
    | '/jobs'
    | '/pipelines'
    | '/reviews'
    | '/schemas'
    | '/settings'
    | '/templates'
    | '/webhooks'
    | '/jobs_/$jobId'
    | '/reviews_/$jobId'
    | '/batches_/$batchId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  BatchesRoute: typeof BatchesRoute
  JobsRoute: typeof JobsRoute
  PipelinesRoute: typeof PipelinesRoute
  ReviewsRoute: typeof ReviewsRoute
  SchemasRoute: typeof SchemasRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  WebhooksRoute: typeof WebhooksRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ReviewsJobIdRoute: typeof ReviewsJobIdRoute
  BatchesBatchIdReviewRoute: typeof BatchesBatchIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews_/$jobId': {
      id: '/reviews_/$jobId'
      path: '/reviews/$jobId'
      fullPath: '/reviews/$jobId'
      preLoaderRoute: typeof ReviewsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches_/$batchId/review': {
      id: '/batches_/$batchId/review'
      path: '/batches/$batchId/review'
      fullPath: '/batches/$batchId/review'
      preLoaderRoute: typeof BatchesBatchIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  BatchesRoute: BatchesRoute,
  JobsRoute: JobsRoute,
  PipelinesRoute: PipelinesRoute,
  ReviewsRoute: ReviewsRoute,
  SchemasRoute: SchemasRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  WebhooksRoute: WebhooksRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ReviewsJobIdRoute: ReviewsJobIdRoute,
  BatchesBatchIdReviewRoute: BatchesBatchIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
