/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/jobs': typeof JobsRoute
  '/pipelines': typeof PipelinesRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/jobs': typeof JobsRoute
  '/pipelines': typeof PipelinesRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/jobs': typeof JobsRoute
  '/pipelines': typeof PipelinesRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/jobs_/$jobId': typeof JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/jobs'
    | '/pipelines'
    | '/schemas'
    | '/settings'
    | '/templates'
    | '/webhooks'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/jobs'
    | '/pipelines'
    | '/schemas'
    | '/settings'
    | '/templates'
    | '/webhooks'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/jobs'
    | '/pipelines'
    | '/schemas'
    | '/settings'
    | '/templates'
    | '/webhooks'
    | '/jobs_/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  JobsRoute: typeof JobsRoute
  PipelinesRoute: typeof PipelinesRoute
  SchemasRoute: typeof SchemasRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  WebhooksRoute: typeof WebhooksRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  JobsRoute: JobsRoute,
  PipelinesRoute: PipelinesRoute,
  SchemasRoute: SchemasRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  WebhooksRoute: WebhooksRoute,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
